[package]
name = "pokeapi_rs"
version = "0.1.0"
authors = ["christopherkarani <christopher.karani@medici.md>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
